---
title: "Proje Rapo : Metin Tunçbilek 200401088"
output: html_notebook
---

# Q1 : Problem tanımı

Şirketimiz \*\* Capital İnvest\*\*. Problemimiz *Şirketimizin artan müşteri sayısından dolayı ve financal analizlerin müşteriye iletiminde oluşan zaman maaliyeti verimliliği azaltmaktadır. Yeni sistem'de Bitcoin geçmiş verilerini R programlama dilinde modeller ile eğitilip tahmin yapması ve arayüz ile müşterilerin kullanımına sunulması hedeflenmektedir. Bu sayede makine öğrenmesi methodlarını kullanarak daha fazla müşteriye hizmet vermek hedeflenmektedir.*  


# Q2 : Proje Amacı

[Bitcoin Historical Data](https://www.kaggle.com/datasets/armanzhalgasbayev/bitcoin-historical-data-2021-2023) adli Kaggle veri setini kullanarak iş problemini *Şirketimizin artan müşteri sayısından dolayı ve financal analizlerin müşteriye iletiminde oluşan zaman maaliyeti verimliliği azaltmaktadır.* ve **LSTM gibi derin öğrenme algoritmaları ile model eğitmeli ve tahmin yaptırmalıyız** yöntemler kullanarak çözmeyi amaçlıyoruz. Bu sayede problemi azaltmayı / yok etmeyi ya da kar arttırımına katkıda bulunmayı planlıyoruz.
